i2k=int(input('      Two thousand notes     : '))
i5h=int(input('      Five hundred notes     : '))
i2h=int(input('      Two hundred notes      : '))
i1h=int(input('      One hundred notes      : '))
i50=int(input('      Fifty rupee notes      : '))
i20=int(input('      Twenty rupee notes     : '))
i10=int(input('      Ten rupee notes        : '))
i5=  int(input('      Five rupee notes/coins : '))
i2=  int(input('      Two rupee coins        : '))
i1=  int(input('      One rupee coins        : '))
print()
print(' -----------------------------------')
print('|           DENOMINATION            |')
print(' -----------------------------------')
print()
print('      {}  x  {}   = {} '.format(i2k,2000,i2k*2000))
print('      {}  x  {}    = {} '.format(i5h,500,i5h*500))
print('      {}  x  {}    = {} '.format(i2h,200,i2h*200))
print('      {}  x  {}    = {} '.format(i1h,100,i1h*100))
print('      {}  x  {}     = {} '.format(i50,50,i50*50))
print('      {}  x  {}     = {} '.format(i20,20,i20*20))
print('      {}  x  {}     = {} '.format(i10,10,i10*10))
print('      {}  x  {}      = {} '.format(i5,5,i5*5))
print('      {}  x  {}      = {} '.format(i2,2,i2*2))
print('      {}  x  {}      = {} '.format(i1,1,i1*1))

s= (i2k*2000)+(i5h*500)+(i2h*200)+(i1h*100)+(i50*50)+(i20*20)+(i10*10)+(i5*5)+(i2*2)+(i1*1)
print(' -----------------------------------')
print('      Total        =',s)